### ISSUE TITLE
Ruby on Railsの表記の統一に関して

### ISSUE THREAD

**Issue by daijiromaeyama** [Techpit-Market/curriculum-textlint#1]
## 概要
Railsの表記を統一したい。

```yml
- pattern:
    - ruby on rails
    - Ruby on rails
    - ruby on Rails
    - RubyOnRails
    expected: Ruby on Rails
```
